# Generated by Django 5.0.3 on 2024-07-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_supplier_pricehistory_productimage_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
